# Generated by Django 4.2 on 2023-04-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderIyem',
            new_name='OrderItem',
        ),
    ]
